### ISSUE TITLE
【複数作業あり】Userの詳細ページを作る

### ISSUE THREAD

**Issue by yuki-snow1823** [yuki-snow1823/diary#104]
ユーザーの詳細ページを作りましょう。

## ページに必要な情報
- ユーザーの名前
- ユーザーの記事一覧

## マイルストーン
1. ユーザーの記事取得のGraphQL Queryを作る（#17 の[このファイル](backend/app/graphql/types/query_type.rb) が参考になりそう）
2. ユーザーの記事一覧取得のGraphQL Queryを作る 同上
3. Reactのuserの詳細ページを作る（一旦何も出なくていい）
4. 3のuserの詳細ページから1のQueryを使ってユーザーの情報を表示
5. 3のuserの詳細ページから2のQueryを使ってユーザーの記事の情報を表示

PRを小分けして作ってください(__)

**Comment by yuki-snow1823** [comment]
記事取得は1でできていた。
他のユーザーの記事を取れないようにする必要はあるが、また別で設計を考えて行う。
きっとその機能は使い回すことになる。編集画面とかでも。

ので、2をやる。（指定したユーザーの記事一覧）

**Comment by yuki-snow1823** [comment]
user取得のquery作成でエラーに当たって対応中

```
{
  "message": "Invalid or incomplete introspection result. Ensure that you are passing \"data\" property of introspection response and no \"errors\" was returned alongside: {}.",
  "stack": "Error: Invalid or incomplete introspection result. Ensure that you are passing \"data\" property of introspection response and no \"errors\" was returned alongside: {}.\n    at devAssert (webpack-internal:///../../../node_modules/graphql/jsutils/devAssert.mjs:7:11)\n    at buildClientSchema (webpack-internal:///../../../node_modules/graphql/utilities/buildClientSchema.mjs:41:266)\n    at eval (webpack-internal:///./components/GraphiQL.tsx:1133:57)"
}
```

これを機にgraphql-rubyをしっかり読み直す

**Comment by yuki-snow1823** [comment]
```
    field :user, Types::UserType, null: false do
```

エラーがなぜ発生したかは説明できないが、構文エラーだった
https://zenn.dev/igz0/articles/3fc43a7c02d9b9

**Comment by yuki-snow1823** [comment]
#123 のマージを待ちつつ、ユーザー詳細のページを作成する

**Comment by yuki-snow1823** [comment]
https://github.com/yuki-snow1823/diary/pull/126

着手。Queryでユーザーを取得した後の型をちゃんと定義できておらず、`user.user.name`みたいになっているが一旦表示はできた。次回直す。
<img width="466" alt="スクリーンショット 2023-08-21 13 29 44" src="https://github.com/yuki-snow1823/diary/assets/59280290/cf824c22-8014-4723-8ed6-d36c1a2badf2">
