### ISSUE TITLE
container presentational patternに従って画面から投稿できる機能を作る

### ISSUE THREAD

**Issue by yuki-snow1823** [yuki-snow1823/diary#56]
@komaitaira さんが提案してくれたアーキテクチャに基づき、画面から記事を投稿する仕組みを作りましょう！

**Comment by yuki-snow1823** [comment]
ついでにここの引数に関して、user_idを先頭に持ってきていただけると嬉しいです。

```
    def resolve(title:, content:, user_id:)
      journal = Journal.create!({
                                  title:,
                                  content:,
                                  user_id:
                                })

      {
        journal:
      }
```

**Comment by yuki-snow1823** [comment]
ログインの確認方法

ユーザーを作成し
```
$ curl -X POST http://localhost:3000/auth -d '[name]=test&[email]=test@example.com&[password]=password&[password_confirmation]=password'
```

ログイン
```
$ curl -X POST -v http://localhost:3000/auth/sign_in -d '[email]=test@example.com&[password]=password'
```

**Comment by yuki-snow1823** [comment]
### タスクの細分化
1. フロントの投稿用ページを作成（デザインは不要）
2. `backend/app/graphql/mutations/create_journal.rb`を使って画面からDBに保存できるようにする
3.  テストを書く

**Comment by yuki-snow1823** [comment]
こんな感じで文字でGraphQLを定義しているが、できれば.graphqlのファイルにしたい。（できたはず）
https://qiita.com/FumioNonaka/items/0c6b711627e3443ff73b

**Comment by yuki-snow1823** [comment]
![IMG_8720](https://github.com/yuki-snow1823/diary/assets/59280290/92c0a4a3-93c4-43b3-bd22-8dd19fb7cf53)

**Comment by yuki-snow1823** [comment]
graphqlをreactで使うときは型定義をする必要があり、それをどう設定するか調べてます。
https://techlife.cookpad.com/entry/2021/03/24/123214

愚直に書くのではなくライブラリが使えたはず

**Comment by yuki-snow1823** [comment]
- スキーマファイルってなんだろう
https://zenn.dev/sky/articles/47b86d3387389d

**Comment by yuki-snow1823** [comment]
:memo: 時間ができたので型定義ファイルの作成方法調べてます

**Comment by yuki-snow1823** [comment]
まさにやりたいことだった
graphqlをヒアドキュメントではなく、ファイルから使いたい
https://techblog.glpgs.com/entry/2022/02/24/131421

**Comment by yuki-snow1823** [comment]
ローカルでは入って動作もしそうだったが、コンテナ上でyarn installすると下記のエラーが出るので調査中

```
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
gyp ERR! stack     at exithandler (node:child_process:427:5)
gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
gyp ERR! System Linux 5.10.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/@parcel/watcher
gyp ERR! node -v v19.3.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok
```

**Comment by yuki-snow1823** [comment]
↑一旦GraphQLの型定義を諦めました。

https://github.com/yuki-snow1823/diary/pull/63 がマージされた後、ユーザーの情報をもって投稿できる実装をやっていきましょう！

**Comment by yuki-snow1823** [comment]
#63 マージされたので、投稿画面の作成やります！
表示をどなたかにお任せしたいですね。ついに投稿機能が...！
